name: 📝 Update README

on:
  push:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  delete_old_runs:
    name: 🧹 Delete old workflow runs
    runs-on: ubuntu-latest

    steps:
      - name: 🧹 Delete old workflow runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/actions/runs \
          --paginate -q '.workflow_runs[] | select(.status != "in_progress" and .status != "queued") | "\(.id)"' | \
          xargs -n1 -I % gh api repos/${{ github.repository }}/actions/runs/% -X DELETE

  markscribe:
    name: 🖋️ README
    runs-on: ubuntu-latest

    steps:
      - name: ⬇ Checkout
        uses: actions/checkout@v7

      - name: 🤖 Regenerate README
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - name: 🤖 Commit generate README changes
        uses: stefanzweifel/git-auto-commit-action@v7
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          commit_message: 🤖 Update generated README
          branch: main
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
